#!/usr/bin/env bash
echo " deploy s3 bucket via cfn"

STACK_NAME="cfn-s3-sample"
aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-west-2 \
--stack-name $STACK_NAME \